# Generated by Django 4.2.3 on 2023-07-08 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.CharField(max_length=100000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=100000)),
            ],
        ),
    ]
